export const sample_foods = [
  {
    id: '1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '7',
    name: 'Junk',
    price: 7,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'food-7.jpg',
    tags: ['FastFood', 'Junk', 'Lunch'],
  },
  {
    
     id: '8',
    name: 'super',
    price: 7,
    cookTime: '30-50',
    favorite: false,
    origins: ['sudan'],
    stars: 4.0,
    imageUrl: 'food-8.jpg',
    tags: ['FastFood', 'super', 'dinner'],
  },
  {
    
    id: '9',
   name: 'best',
   price: 5, 
   cookTime: '30-50',
   favorite: false,
   origins: ['sudan'],
   stars: 4.0,
   imageUrl: 'food-9.jpg',
   tags: ['FastFood', 'best', 'dinner'],
 },
 {
  id: '10',
 name: 'processed',
 price: 5,  
 cookTime: '40-50',
 favorite: true,
 origins: ['sudan'],
 stars: 4.0,
 imageUrl: 'food-10.jpg',
 tags: ['FastFood', 'processed', 'dinner'],
},
{
  id: '11',
 name: 'puerto',
 price: 5, 
 cookTime: '40-50',
 favorite: true,
 origins: ['sudan'],
 stars: 4.0,
 imageUrl: 'food-11.jpg',
 tags: ['FastFood', 'puerto', 'dinner'],
},
{
  id: '12',
 name: 'vegetables',
 price: 5,
 cookTime: '30-50',
 favorite: true,
 origins: ['sudan'],
 stars: 4.0,
 imageUrl: 'food-12.jpg',
 tags: ['FastFood', 'vegetables', 'dinner'],
},
{
  id: '13',
 name: 'invented',
 price: 15,
 cookTime: '30-50',
 favorite: true,
 origins: ['America'],
 stars: 4.0,
 imageUrl: 'food-13.jpg',
 tags: ['FastFood', 'invented', 'dinner'],
},
{
  id: '14',
 name: 'fruits',
 price: 15,
 cookTime: '30-50',
 favorite: true,
 origins: ['sudan'],
 stars: 4.0,
 imageUrl: 'food-14.jpg',
 tags: ['FastFood', 'invented', 'dinner'],
},
{
  id: '15',
 name: 'Definition',
 price: 15,
 cookTime: '30-50',
 favorite: true,
 origins: ['sudan'],
 stars: 4.0,
 imageUrl: 'food-15.jpg',
 tags: ['FastFood', 'Definition', 'dinner'],
},
{
  id: '16',
 name: 'Delicioso',
 price: 10,
 cookTime: '40-50',
 favorite: true,
 origins: ['sudan'],
 stars: 4.0,
 imageUrl: 'food-17.jpg',
 tags: ['FastFood', 'Delicioso', 'dinner'],
},
{
  id: '17',
 name: 'beneficios',
 price: 5,
 cookTime: '40-50',
 favorite: true,
 origins: ['sudan'],
 stars: 4.0,
 imageUrl: 'food-19.jpg',
 tags: ['FastFood', 'beneficios', 'dinner'],
},
];

export const sample_tags = [
  { name: 'All', count: 17 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 3 },
  { name: 'Junk', count: 6 },
  { name: 'super', count: 3 },
  { name: 'best', count: 2 },
  { name: 'processed', count: 10 },
  { name: 'puerto', count: 13 },
  { name: 'vegetables', count: 1 },
  { name: 'invented', count: 12 },
  { name: 'fruits', count: 6 },
  { name: 'Definition', count: 11 },
  { name: 'Delicioso', count: 9 },
  { name: 'beneficios', count: 17 },                  
];

export const sample_users = [
  {
    id: 1,
    name: 'umran abdo',
    email: 'umranabdo112@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'omran abdo',
    email: 'omranabdualaziz@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: true,
  },
];